source.. = src/,\
           test/
output.. = bin/
bin.includes = plugin.xml,\
               META-INF/,\
               .,\
               icons/,\
               lib/jfreechart-1.5.3.jar,\
               lib/jcommon-1.0.24.jar,\
               lib/json-java.jar,\
               build.properties
src.includes = src/,\
               plugin.xml,\
               META-INF/,\
               icons/,\
               lib/,\
               build.properties